version: "3"

services:

  secrets:
    build:
      context: .
      args:
        ALPINE_VERSION: 3.15
    tty: true
    volumes:
      - ./src:/home
    environment:
      - SECRETS_PUBLIC_KEY
      - SECRETS_PRIVATE_KEY
